/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:70de1336-789c-481c-9588-63e530caeb15",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_YX5c0i4HS",
    "aws_user_pools_web_client_id": "1itfeugbgaf5gkkq84ud3pg11i",
    "oauth": {}
};


export default awsmobile;
